version: "2"
services:
  app:
    command: "yarn start"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3040
    ports:
      - "3040:3000"
    restart: always
    container_name: aq-water-food-security
